# Generated by Django 5.2.6 on 2025-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(unique=True)),
                ("full_text", models.TextField()),
                ("summary", models.TextField()),
                ("crawl_date", models.DateTimeField(auto_now_add=True)),
                ("article_date", models.DateTimeField()),
            ],
        ),
    ]
